services:
  api:
    image: mfascinante-backend
    container_name: mfascinante-api
    build: .
    ports:
      - "4444:4444"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: always